#!/usr/bin/env bash
# Generated by the HyperDNS controller for one enrolled edge identity.
set -euo pipefail
umask 077

PANEL_BASE={{.PanelBase}}
CONTROLLER_URL={{.ControllerURL}}
NODE_ID={{.NodeID}}
NODE_IP={{.NodeIP}}
JOIN_TOKEN={{.JoinToken}}

if [ "$(id -u)" -ne 0 ]; then
    echo 'Run this installer through sudo bash.' >&2
    exit 1
fi
for tool in curl systemctl install mktemp uname ss grep readlink; do
    command -v "$tool" >/dev/null || { echo "Missing required command: $tool" >&2; exit 1; }
done
if systemctl is-active --quiet hyperdns; then
    echo 'An existing standalone HyperDNS service is running on this host.' >&2
    exit 1
fi
case "$(uname -m)" in
    x86_64|amd64) ARCH=amd64 ;;
    aarch64|arm64) ARCH=arm64 ;;
    *) echo 'Unsupported CPU architecture.' >&2; exit 1 ;;
esac

# Fetch before changing the host resolver or service. Downloads are authorised
# by the same one-time join token and delivered over the panel's trusted HTTPS.
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
curl --fail --location --silent --show-error \
    "$PANEL_BASE/edge/binary/$NODE_ID/$JOIN_TOKEN/$ARCH" -o "$WORK/hyperdns"
test -s "$WORK/hyperdns"

install -d -m 700 /opt/hyperdns
cat > /opt/hyperdns/cluster-ca.pem <<'HYPERDNS_CLUSTER_CA'
{{.CAPEM}}HYPERDNS_CLUSTER_CA
chmod 644 /opt/hyperdns/cluster-ca.pem
printf '%s\n' "$JOIN_TOKEN" > /opt/hyperdns/node.join
chmod 600 /opt/hyperdns/node.join
unset JOIN_TOKEN

# Match the standalone installer's port-53 setup without replacing the host's
# upstream DNS servers. An unrelated listener remains an actionable error.
if ss -H -luntp '( sport = :53 )' | grep -q systemd-resolved; then
    install -d -m 755 /etc/systemd/resolved.conf.d
    printf '[Resolve]\nDNSStubListener=no\n' > /etc/systemd/resolved.conf.d/hyperdns-edge.conf
    chmod 644 /etc/systemd/resolved.conf.d/hyperdns-edge.conf
    systemctl restart systemd-resolved
    if [ "$(readlink -f /etc/resolv.conf)" = /run/systemd/resolve/stub-resolv.conf ]; then
        ln -sfn /run/systemd/resolve/resolv.conf /etc/resolv.conf
    fi
fi
if ss -H -luntp '( sport = :53 )' | grep -q .; then
    echo 'Port 53 is still occupied. Inspect: ss -luntp ( sport = :53 )' >&2
    exit 1
fi

# Open the local firewall only when one is already active. Cloud-provider
# firewalls still need their own inbound rules for the same ports.
if command -v ufw >/dev/null && ufw status | grep -q '^Status: active'; then
    for port in 53/udp 53/tcp 80/tcp 443/tcp 5222/tcp 5223/tcp 2099/tcp 8393/tcp; do
        ufw allow "$port" >/dev/null
    done
elif command -v firewall-cmd >/dev/null && firewall-cmd --state 2>/dev/null | grep -q running; then
    for port in 53/udp 53/tcp 80/tcp 443/tcp 5222/tcp 5223/tcp 2099/tcp 8393/tcp; do
        firewall-cmd --permanent --add-port="$port" >/dev/null
    done
    firewall-cmd --reload >/dev/null
fi

install -m 755 "$WORK/hyperdns" /opt/hyperdns/hyperdns.new
mv -f /opt/hyperdns/hyperdns.new /opt/hyperdns/hyperdns
cat > /etc/systemd/system/hyperdns-edge.service <<EOF
[Unit]
Description=HyperDNS Edge Node
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/hyperdns
ExecStart=/opt/hyperdns/hyperdns -role edge -server -node-id $NODE_ID -controller-url $CONTROLLER_URL -cluster-ca /opt/hyperdns/cluster-ca.pem -join-token-file /opt/hyperdns/node.join -public-ip $NODE_IP -db /opt/hyperdns/edge-data.db -key /opt/hyperdns/edge-master.key -cluster-state /opt/hyperdns/cluster-node
Restart=always
RestartSec=3s
LimitNOFILE=65535
TimeoutStopSec=15s

[Install]
WantedBy=multi-user.target
EOF
chmod 644 /etc/systemd/system/hyperdns-edge.service
systemctl daemon-reload
systemctl enable --now hyperdns-edge
sleep 2
systemctl --no-pager --full status hyperdns-edge
echo 'HyperDNS edge installed. Check the Nodes tab for sync and DNS probe status.'
